drop table like_review;
drop table review;
drop table has_feature;
drop table coupon;
drop table rate;
drop table reservation;
drop table features;
drop table villa;
drop table owners;
alter table manager drop foreign key mid;
drop table manager;
drop table users;
